MyCarier/Models/PersonInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCarier.Models
{
    public class PersonInfo
    {
        [Key]
        public int Id { get; set; }

        [Required, StringLength(25)]
        public string Name { get; set; }

        [Required, StringLength(25)]
        public string Surname { get; set; }

        [StringLength(60)]
        public string Title { get; set; }

        [StringLength(25)]
        public string City { get; set; }

        [StringLength(25)]
        public string Country { get; set; }

        [Required, StringLength(60)]
        public string Email { get; set; }

        [StringLength(25)]
        public string Phone { get; set; }

        [StringLength(50), DisplayName("Profile Photo")]
        public string PhotoImageName { get; set; }

        [StringLength(350), DisplayName("Addtional Info")]
        public string AddtionalInfo { get; set; }
    }
}

MyCarier/Controllers/PersonInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyCarier.Models;
using MyCarier.Filters;

namespace MyCarier.Controllers
{
    [AuthFilter, ExcFilter, ActFilter]
    public class PersonInfoController : Controller
    {
        private DatabaseContext db = new DatabaseContext();


        // GET: PersonInfo/Edit
        public ActionResult Edit()
        {

            if (Session["CurrentUser"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string email = Session["CurrentUser"].ToString();
            
            PersonInfo personInfo = db.PersonInfos.FirstOrDefault(x => x.Email == email);
            if (personInfo == null)
            {
                return HttpNotFound();
            }
            return View(personInfo);
        }

        // POST: PersonInfo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(PersonInfo personInfo, HttpPostedFileBase uploaded)
        {
            if (ModelState.IsValid)
            {
                db.Entry(personInfo).State = EntityState.Modified;
                
                if (uploaded != null)
                {
                    string filepath =
                        Server.MapPath("~/images") + "/" + personInfo.Id.ToString() + ".png";

                    uploaded.SaveAs(filepath);

                    personInfo.PhotoImageName = personInfo.Id.ToString() + ".png";
                }

                if(db.SaveChanges() > 0)
                {
                    Session["CurrentUser"] = personInfo.Email;
                }
                
                return RedirectToAction("Edit");
            }
            return View(personInfo);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyCarier/Views/PersonInfo/Edit.cshtml
@model MyCarier.Models.PersonInfo

@{
    ViewBag.Title = "Edit";
    ViewBag.Header = "Edit Person Info";
    ViewBag.HeaderIcon = "user";
    ViewBag.NavPersonInfo = "w3-blue";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script src="~/Scripts/ckeditor/ckeditor.js"></script>
<div class="w3-container w3-padding-16">
    <div class="col-md-12">

        @using (Html.BeginForm("Edit", "PersonInfo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Person Info</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.Email)

                <div class="form-group">
                    <div class="col-md-2">
                        &nbsp;
                    </div>
                    <div class="col-md-2 col-md-offset-4">
                        <img src="~/images/@Model.PhotoImageName" class="img-rounded img-thumbnail img-responsive"/>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhotoImageName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="hidden" name="PhotoImageName" value="@Model.PhotoImageName" />
                        <input type="file" id="uploaded" name="uploaded" class="form-control" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AddtionalInfo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.AddtionalInfo)
                        @Html.ValidationMessageFor(model => model.AddtionalInfo, "", new { @class = "text-danger" })
                        <script>
                            CKEDITOR.replace("@Html.NameFor(model => model.AddtionalInfo)");
                        </script>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-warning" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>